export const fallbackCategories = [
  { name: 'Miền Bắc', slug: 'mien-bac' },
  { name: 'Miền Trung', slug: 'mien-trung' },
  { name: 'Miền Nam', slug: 'mien-nam' },
  { name: 'Miền Tây', slug: 'mien-tay' },
  { name: 'Các loại hạt', slug: 'cac-loai-hat', parentSlug: 'mien-nam' },
  { name: 'Các loại mắm', slug: 'cac-loai-mam', parentSlug: 'mien-tay' },
  { name: 'Các loại khô', slug: 'cac-loai-kho', parentSlug: 'mien-tay' },
  { name: 'Nem chua', slug: 'nem-chua', parentSlug: 'mien-trung' },
  { name: 'Thịt gác bếp', slug: 'thit-gac-bep', parentSlug: 'mien-bac' },
];

export const fallbackProducts = [
  {
    name: 'Hạt Điều Rang Tỏi Ớt Hủ 500gr, Loại 1 Nhập Từ Bình Phước',
    slug: 'hat-dieu-rang-toi-ot-hu-500gr-loai-1-nhap-tu-binh-phuoc',
    categorySlug: 'cac-loai-hat',
    regularPrice: 250000,
    salePrice: 176000,
    image: '/assets/uploads/2025/09/hat-dieu-rang-toi-ot-min-400x400.jpg',
    featured: true,
  },
  {
    name: 'Thịt Vai Giòn Lợn Bản Gác Bếp Siêu Ngon',
    slug: 'thit-vai-gion-lon-ban-gac-bep-sieu-ngon',
    categorySlug: 'mien-bac',
    regularPrice: 500000,
    salePrice: 450000,
    image: '/assets/uploads/2025/09/mb-1-600x400.jpg',
    featured: true,
  },
  {
    name: 'Nem Chua Thanh Hóa Gia Truyền',
    slug: 'nem-chua-thanh-hoa-gia-truyen',
    categorySlug: 'mien-trung',
    regularPrice: 48000,
    salePrice: 28000,
    image: '/assets/uploads/2025/09/nem-chua-thanh-hoa-vuong-vifoodshop-300x300.jpg',
    featured: true,
    variants: [
      { name: 'Hộp nhỏ', regularPrice: 28000, salePrice: 28000 },
      { name: 'Hộp lớn', regularPrice: 48000, salePrice: 48000 },
    ],
  },
  {
    name: 'Mắm cá linh Sông Hương hũ 400g',
    slug: 'mam-ca-linh-song-huong-hu-400g',
    categorySlug: 'cac-loai-mam',
    regularPrice: 25000,
    salePrice: 1000,
    image: '/assets/uploads/2025/09/mam-ca-linh-song-huong-hu-400g-201902271415517675-300x225.jpg',
    featured: true,
  },
  {
    name: 'Khô cá lóc đồng - Đặc sản miền Tây 500g',
    slug: 'kho-ca-loc-dong-dac-san-mien-tay-500g',
    categorySlug: 'cac-loai-kho',
    regularPrice: 150000,
    salePrice: 103000,
    image: '/assets/uploads/2025/09/kho-ca-loc-chien-nuong-dac-san-mien-tay-02.jpg',
    featured: true,
  },
  {
    name: 'Nem Chua Thanh Hóa Gia Truyền (Sao chép)',
    slug: 'nem-chua-thanh-hoa-gia-truyen-sao-chep',
    categorySlug: 'mien-trung',
    regularPrice: 48000,
    salePrice: 28000,
    image: '/assets/uploads/2025/09/nem-chua-coi-thanh-hoa-vifoodshop.jpg',
  },
];

export const fallbackPages = [
  {
    type: 'page',
    title: 'Giới thiệu',
    slug: 'gioi-thieu',
    excerpt: 'Đặc Sản Việt kết nối hương vị quê hương đến mọi miền.',
    body: '<p>Đặc Sản Việt tuyển chọn những món ăn đặc trưng từ khắp các vùng miền, giữ trọn hương vị quê nhà và giao đến tận tay khách hàng.</p>',
    imageUrl: '/assets/uploads/2025/09/about5-1024x576.jpg',
  },
  {
    type: 'page',
    title: 'Liên hệ',
    slug: 'lien-he',
    excerpt: 'Liên hệ tư vấn mua hàng.',
    body: '<p>Địa chỉ: 56 Hoàng Diệu 2, Phường Thủ Đức, TP Hồ Chí Minh</p><p>Hotline: (028) 38 212 430</p>',
  },
  {
    type: 'post',
    title: 'Củ Hủ Dừa Bến Tre - Tinh hoa giữa lòng xứ dừa',
    slug: 'cu-hu-dua-ben-tre-tinh-hoa-giua-long-xu-dua',
    excerpt: 'Khi nhắc đến Bến Tre, người ta nghĩ ngay đến những rặng dừa xanh bạt ngàn.',
    body: '<p>Củ hủ dừa là phần non nhất của cây dừa, giòn ngọt và thường xuất hiện trong các món gỏi, xào hoặc ăn kèm hải sản.</p>',
    imageUrl: '/assets/uploads/2025/09/cuhudua.png',
  },
  {
    type: 'post',
    title: 'Khai trương tưng bừng - Ngập tràn ưu đãi',
    slug: 'khai-truong-tung-bung-ngap-tran-uu-dai',
    excerpt: 'Đặc Sản Việt trân trọng thông báo chương trình khai trương.',
    body: '<p>Nhiều ưu đãi hấp dẫn cho khách hàng trong tuần lễ khai trương.</p>',
    imageUrl: '/assets/thumbKhaiTruong.png',
  },
  {
    type: 'post',
    title: 'Chào tất cả mọi người!',
    slug: 'tin-tuc',
    excerpt: 'Tin tức và câu chuyện ẩm thực từ Đặc Sản Việt.',
    body: '<p>Cảm ơn bạn đã ghé thăm Đặc Sản Việt.</p>',
  },
];
